---
- name: Create datavg
  community.general.lvg:
    vg: data
    pvs: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1

- name: Create rabbitmq lv
  community.general.lvol:
    vg: data
    lv: rabbitmq
    size: 95G

- name: Format rabbitmq lv
  community.general.filesystem:
    fstype: xfs
    dev: /dev/data/rabbitmq

- name: Mount rabbitmq drive
  ansible.posix.mount:
    path: /var/lib/rabbitmq/
    src: /dev/data/rabbitmq
    fstype: xfs
    boot: true
    state: mounted

# Start RabbitMQ
- name: RabbitMQ Team keyring
  ansible.builtin.get_url:
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA
    dest: /usr/share/keyrings/com.rabbitmq.team.asc
    checksum: sha256:f06ccb0568a012e751e276c15b733494147fbb0663c79ab77f3574def4767f99
    mode: "0644"

- name: Cloudsmith modern Erlang repository keyring
  ansible.builtin.get_url:
    url: https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key
    dest: /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc
    checksum: sha256:84df2e5fd80d464c3eb9acd2f751b2f6a723438200915dd50fbf12f08698e4ec
    mode: "0644"

- name: Cloudsmith RabbitMQ repository keyring
  ansible.builtin.get_url:
    url: https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key
    dest: /usr/share/keyrings/rabbitmq.9F4587F226208342.asc
    checksum: sha256:17b3eeb98b7aabe659b0e2579715d1ae4e328b58a401434599495779c59ac73a
    mode: "0644"

- name: Add Erlang repo
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu noble main
      deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu noble main
    state: present

- name: Add RabbitMQ repo
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.asc] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu noble main
      deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.asc] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu noble main
    state: present

- name: Install Erlang
  ansible.builtin.package:
    name:
      - erlang-base
      - erlang-asn1
      - erlang-crypto
      - erlang-eldap
      - erlang-ftp
      - erlang-inets
      - erlang-mnesia
      - erlang-os-mon
      - erlang-parsetools
      - erlang-public-key
      - erlang-runtime-tools
      - erlang-snmp
      - erlang-ssl
      - erlang-syntax-tools
      - erlang-tftp
      - erlang-tools
      - erlang-xmerl
    state: present

- name: Install RabbitMQ
  ansible.builtin.package:
    name:
      - rabbitmq-server
    state: present
  register: rabbitmq_install

- name: Disable RabbitMQ Service # noqa: no-handler
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: stopped
    enabled: false
  when: rabbitmq_install.changed

# Ownership after install because we need the rabbitmq user
- name: Own rabbitmq drive
  ansible.builtin.file:
    path: /var/lib/rabbitmq/
    owner: rabbitmq
    group: rabbitmq
    mode: "0700"

- name: Own rabbitmq config dir
  ansible.builtin.file:
    path: /etc/rabbitmq/
    owner: rabbitmq
    group: rabbitmq
    mode: "0700"

- name: Create RabbitMQ Cluster Server Certificates
  ansible.builtin.command: >-
    step ca certificate {{ ansible_fqdn }}
    /etc/rabbitmq/rabbitmq-cluster-server.crt
    /etc/rabbitmq/rabbitmq-cluster-server.key
    --ca-url https://step-ca.us-homelab1.hl.rmb938.me:8443
    --root /usr/local/share/ca-certificates/smallstep-homelab-prod.crt
  args:
    creates: "/etc/rabbitmq/rabbitmq-cluster-server.crt"

- name: Own RabbitMQ Cluster Server Certificates
  ansible.builtin.file:
    path: /etc/rabbitmq/{{ item }}
    owner: rabbitmq
    group: rabbitmq
    mode: "0600"
  with_items:
    - rabbitmq-cluster-server.crt
    - rabbitmq-cluster-server.key

- name: Cron to renew RabbitMQ Cluster Server Certificates
  ansible.builtin.cron:
    name: "renew rabbitmq cluster certificates"
    special_time: "hourly"
    # Rekey needs to happen against the CA, RA's don't support rekey
    # https://smallstep.com/docs/step-ca/registration-authority-ra-mode/#stepcas-limitations
    job: >-
      step ca rekey /etc/rabbitmq/rabbitmq-cluster-server.crt
      /etc/rabbitmq/rabbitmq-cluster-server.key
      --ca-url https://step-ca.us-homelab1.hl.rmb938.me
      --root /usr/local/share/ca-certificates/smallstep-homelab-prod.crt
      --force --expires-in 720h --exec "systemctl try-reload-or-restart rabbitmq-server"
    state: present

- name: RabbitMQ Plugins
  ansible.builtin.template:
    src: etc/rabbitmq/enabled_plugins
    dest: /etc/rabbitmq/enabled_plugins
    mode: "0600"
    owner: rabbitmq
    group: rabbitmq
  register: rabbitmq_plugins

- name: Make Sure Erlang SSL Exists
  ansible.builtin.stat:
    # This will change between erlang versions so we want this to fail
    # if it doesn't
    path: /usr/lib/erlang/lib/ssl-11.2.7/ebin
  register: erlang_ssl

- name: Failing if Erlang SSL doesn't exist # noqa: no-handler
  ansible.builtin.fail:
    msg: "Erlang SSL folder doesn't exist, version may have changed."
  when: not erlang_ssl.stat.exists

- name: RabbitMQ Env
  ansible.builtin.template:
    src: etc/rabbitmq/rabbitmq-env.conf
    dest: /etc/rabbitmq/rabbitmq-env.conf
    mode: "0600"
    owner: rabbitmq
    group: rabbitmq
  register: rabbitmq_env

- name: RabbitMQ Inter Node TLS Config
  ansible.builtin.template:
    src: etc/rabbitmq/inter_node_tls.config
    dest: /etc/rabbitmq/inter_node_tls.config
    mode: "0600"
    owner: rabbitmq
    group: rabbitmq
  register: rabbitmq_inter_node_tls_config
# End RabbitMQ

# Start Consul Template RabbitMQ
- name: Add rabbitmq to sudoers
  community.general.sudoers:
    name: rabbitmq
    user: rabbitmq
    nopassword: true
    validation: required
    commands:
      - /usr/bin/systemctl reload-or-restart rabbitmq-server
    state: present

- name: Configure Consul Template for RabbitMQ
  ansible.builtin.template:
    src: etc/consul-template/consul-template-rabbitmq.hcl
    dest: /etc/consul-template/consul-template-rabbitmq.hcl
    mode: "0644"
    owner: rabbitmq
    group: rabbitmq
  register: consul_template_rabbitmq_config

- name: Create Consul Template for RabbitMQ Templates directory
  ansible.builtin.file:
    path: /etc/consul-template/templates/rabbitmq/
    state: directory
    mode: "0744"
    owner: rabbitmq
    group: rabbitmq

- name: Place Consul Template for RabbitMQ Templates Files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/consul-template/templates/rabbitmq/{{ item | basename }}"
    mode: "0644"
    owner: rabbitmq
    group: rabbitmq
  with_fileglob:
    - ../files/etc/consul-template/templates/rabbitmq/*.ctmpl
  register: consul_template_rabbitmq_templates_files

- name: Place Consul Template for RabbitMQ Templates Templates
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/consul-template/templates/rabbitmq/{{ item | basename }}"
    mode: "0644"
    owner: rabbitmq
    group: rabbitmq
  with_fileglob:
    - ../templates/etc/consul-template/templates/rabbitmq/*.ctmpl
  register: consul_template_rabbitmq_templates

- name: Consul Template for RabbitMQ SystemD
  ansible.builtin.template:
    src: etc/systemd/system/consul-template-rabbitmq.service
    dest: /etc/systemd/system/consul-template-rabbitmq.service
    mode: "0644"
  register: consul_template_rabbitmq_systemd

- name: Consul Template for RabbitMQ systemd # noqa: no-handler
  ansible.builtin.systemd:
    daemon_reload: true
  when: consul_template_rabbitmq_systemd.changed

- name: Start and enable Consul Template for RabbitMQ
  ansible.builtin.systemd:
    name: consul-template-rabbitmq
    state: started
    enabled: true

- name: Restart Consul Template for RabbitMQ if config changed # noqa: no-handler
  ansible.builtin.systemd:
    name: consul-template-rabbitmq
    state: reloaded
  when: consul_template_rabbitmq_templates.changed or
    consul_template_rabbitmq_config.changed or
    consul_template_rabbitmq_templates_files.changed
# End Consul Template RabbitMQ

# TODO: remove this
- name: Restart RabbitMQ Service # noqa: no-handler
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: restarted
  when: rabbitmq_plugins.changed or
    rabbitmq_env.changed or
    rabbitmq_inter_node_tls_config.changed
# End RabbitMQ
