---
- name: Create datavg
  community.general.lvg:
    vg: data
    pvs: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1

- name: Create rabbitmq lv
  community.general.lvol:
    vg: data
    lv: rabbitmq
    size: 95G

- name: Format rabbitmq lv
  community.general.filesystem:
    fstype: xfs
    dev: /dev/data/rabbitmq

- name: Mount rabbitmq drive
  ansible.posix.mount:
    path: /var/lib/rabbitmq/
    src: /dev/data/rabbitmq
    fstype: xfs
    boot: true
    state: mounted

# Start RabbitMQ
- name: RabbitMQ Team keyring
  ansible.builtin.get_url:
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA
    dest: /usr/share/keyrings/com.rabbitmq.team.asc
    checksum: sha256:f06ccb0568a012e751e276c15b733494147fbb0663c79ab77f3574def4767f99
    mode: "0644"

- name: Cloudsmith modern Erlang repository keyring
  ansible.builtin.get_url:
    url: https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key
    dest: /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc
    checksum: sha256:84df2e5fd80d464c3eb9acd2f751b2f6a723438200915dd50fbf12f08698e4ec
    mode: "0644"

- name: Cloudsmith RabbitMQ repository keyring
  ansible.builtin.get_url:
    url: https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key
    dest: /usr/share/keyrings/rabbitmq.9F4587F226208342.asc
    checksum: sha256:17b3eeb98b7aabe659b0e2579715d1ae4e328b58a401434599495779c59ac73a
    mode: "0644"

- name: Add Erlang repo
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu noble main
      deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu noble main
    state: present

- name: Add RabbitMQ repo
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.asc] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu noble main
      deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.asc] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu noble main
    state: present

- name: Install Erlang
  ansible.builtin.package:
    name:
      - erlang-base
      - erlang-asn1
      - erlang-crypto
      - erlang-eldap
      - erlang-ftp
      - erlang-inets
      - erlang-mnesia
      - erlang-os-mon
      - erlang-parsetools
      - erlang-public-key
      - erlang-runtime-tools
      - erlang-snmp
      - erlang-ssl
      - erlang-syntax-tools
      - erlang-tftp
      - erlang-tools
      - erlang-xmerl
    state: present

- name: Install RabbitMQ
  ansible.builtin.package:
    name:
      - rabbitmq-server
    state: present
  register: rabbitmq_install

- name: Disable RabbitMQ Service # noqa: no-handler
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: stopped
    enabled: false
  when: rabbitmq_install.changed

# Ownership after install because we need the rabbitmq user
- name: Own rabbitmq drive
  ansible.builtin.file:
    path: /var/lib/rabbitmq/
    owner: rabbitmq
    group: rabbitmq
    mode: "0700"

- name: Enable RabbitMQ Plugins
  ansible.builtin.template:
    src: etc/rabbitmq/enabled_plugins
    dest: /etc/rabbitmq/enabled_plugins
    mode: "0600"
    owner: rabbitmq
    group: rabbitmq
  register: rabbitmq_plugins

- name: Enable RabbitMQ Env
  ansible.builtin.template:
    src: etc/rabbitmq/rabbitmq-env.conf
    dest: /etc/rabbitmq/rabbitmq-env.conf
    mode: "0600"
    owner: rabbitmq
    group: rabbitmq
  register: rabbitmq_env

- name: Enable RabbitMQ Config
  ansible.builtin.template:
    src: etc/rabbitmq/rabbitmq.conf
    dest: /etc/rabbitmq/rabbitmq.conf
    mode: "0600"
    owner: rabbitmq
    group: rabbitmq
  register: rabbitmq_config

- name: Erlang Cookie
  ansible.builtin.copy:
    # TODO: move to a consul template
    content: "this-is-my-random-erlang-cookie"
    dest: /var/lib/rabbitmq/.erlang.cookie
    mode: "0600"
    owner: rabbitmq
    group: rabbitmq
  register: rabbitmq_cookie

- name: Restart RabbitMQ Service # noqa: no-handler
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: restarted
  when: rabbitmq_plugins.changed or
    rabbitmq_env.changed or
    rabbitmq_config.changed or
    rabbitmq_cookie.changed
# End RabbitMQ
